---
title: "Plotting priors vs posteriors for our survival model"
author: 'eleanorjackson'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
format: 
  gfm:
    toc: true
editor: source
execute:
  warning: false
---

```{r setup}
#| include: false

file_name <- knitr::current_input()

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.rmarkdown$", "", basename(file_name)), 
           "/", sep = "")
)

set.seed(123)
ggplot2::theme_set(ggplot2::theme_bw(base_size = 13))
```

```{r}
library("tidyverse")
library("tidybayes")
library("brms")
library("ggtext")
```

```{r}
mod_surv <-
  readRDS(here::here("output", "models", 
                     "survival_model.rds"))
```

```{r}
prior_draws <- 
  prior_draws(mod_surv) %>% 
  select(contains("b"))
  
post_draws <- 
  as_draws_df(mod_surv, variable = "^b_", regex = TRUE)

prior_post <- 
  bind_rows(prior = prior_draws, 
          posterior = post_draws,
          .id = "dist") %>% 
  pivot_longer(cols = contains("b")) %>% 
  mutate(parameter = str_split_i(string = name, 
                                 pattern ="_", i = 2)) %>% 
  mutate(type = case_when(
    grepl("logged", name) ~ "log &lambda;, Logged forest",
    grepl("primary", name) ~ "log &lambda;, Old-growth forest",
    grepl("b_dbase_mean_sc", name) ~ "&beta;, Basal diameter")) %>% 
  mutate(parameter = str_remove(string = parameter, 
                                 pattern ="logged")) %>% 
  mutate(parameter = str_remove(string = parameter, 
                                 pattern ="primary")) 
```

```{r}
pal <-
  c("log &lambda;, Logged forest" = "#e69f00", 
    "log &lambda;, Old-growth forest" = "#009e73",
    "&beta;, Basal diameter" = "#56B4E9")

prior_post %>% 
  filter(value > -25) %>% 
  filter(value < 25) %>% 
  mutate(dist = str_to_sentence(dist)) %>%
  mutate(dist = factor(dist, levels = c("Prior", "Posterior"))) %>%
  ggplot(aes(x = value, fill = type)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~dist, scales = "free", ncol = 1) +
  scale_fill_manual(values = pal, breaks = ~ .x[!is.na(.x)]) +
  theme(legend.title = element_blank(),
        legend.text = element_markdown()) 
```
