---
title: "Create a figure exlaining the analysis?"
author: 'eleanorjackson'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
format: 
  gfm:
    toc: true
editor: source
execute:
  warning: false
---

```{r setup}
#| include: false

file_name <- knitr::current_input()

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.rmarkdown$", "", basename(file_name)), 
           "/", sep = "")
)

set.seed(123)
ggplot2::theme_set(ggplot2::theme_classic(base_size = 20))
```

```{r}
library("tidyverse")
library("patchwork")
library("tidybayes")
library("modelr")
```


# Growth

```{r}
data <-
  readRDS(here::here("data",
                     "derived",
                     "data_cleaned.rds"))

well_sampled_trees <-
  data %>%
  group_by(plant_id) %>%
  summarise(records = sum(!is.na(dbase_mean))) %>%
  filter(records > 2)

growth_data <-
  data %>%
  filter(survival == 1) %>%
  drop_na(dbase_mean) %>% 
  filter(plant_id %in% well_sampled_trees$plant_id)
```

```{r}
growth_model <- readRDS(here::here("output",
                                   "models",
                                   "priors2",
                                   "growth_model_impute_base_nodbh.rds"))
```

```{r}
sp_n <- 
  growth_data %>% 
  group_by(genus_species, forest_type) %>% 
  summarise(n = n_distinct(plant_id),
            .groups = "drop") %>% 
  pivot_wider(names_from = forest_type, values_from = n) %>% 
  arrange(-secondary)

sp_n

sp_1 <- 
  sp_n %>% 
  pluck(1, 4) %>% 
  paste()
```

```{r}
keys <- 
  growth_data %>%
  filter(genus_species == sp_1) %>% 
  select(plant_id, forest_type) %>%
  distinct(plant_id, .keep_all = TRUE) %>%
  mutate(plant_id = droplevels(plant_id))

growth_data_sp1 <- 
  growth_data %>% 
  filter(genus_species == sp_1)

sp1_preds <- 
  growth_data_sp1 %>%
  data_grid(years = seq_range(years, n = 20),
            genus_species = sp_1,
            plant_id = droplevels(unique(keys$plant_id))) %>%
  left_join(keys) %>%
  filter(forest_type == "secondary") %>% 
  add_epred_draws(growth_model,
                  allow_new_levels = FALSE) 
```

## First panel

```{r}
plant_1 <- 
  growth_data_sp1 %>% 
  filter(forest_type == "secondary") %>% 
  group_by(plant_id) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  pluck(1, 5) %>% 
  paste()

growth_data_pl1 <-
  growth_data_sp1 %>% 
  filter(plant_id == plant_1)

pl1_preds <-
  sp1_preds %>% 
  filter(plant_id == plant_1)

p1 <- 
  ggplot() +
  stat_lineribbon(data = pl1_preds,
                  aes(x = years, y = .epred,
                      group = plant_id),
                  colour = "forestgreen",
                  .width = 0,
                  linewidth = 1,
                  alpha = 0.4) +
  geom_point(data = growth_data_pl1,
             aes(x = years, y = dbase_mean),
             shape = 4, stroke = 0.75, size = 2,
             colour = "forestgreen") +
  theme(legend.position = "none") +
  ylab("Basal diameter cm") +
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

p1
```

## Second panel

```{r}

growth_data_sp1_s <-
  growth_data_sp1 %>% 
  filter(forest_type == "secondary")

sp1_preds_s <-
  sp1_preds %>% 
  filter(forest_type == "secondary")

p2 <- 
  ggplot() +
  stat_lineribbon(data = sp1_preds_s,
                  aes(x = years, y = .epred,
                      group = plant_id),
                  colour = "forestgreen",
                  .width = 0,
                  linewidth = 1,
                  alpha = 0.3) +
  stat_lineribbon(data = sp1_preds_s,
                  aes(x = years, y = .epred),
                  .width = 0,
                  linewidth = 1,
                  alpha = 1,
                  linetype = 2) +
  theme(legend.position = "none") +
  ylab("Basal diameter cm") +
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

p2
```

## Third panel

```{r}
all_preds <- 
  growth_data %>% 
  drop_na(dbase_mean) %>% 
  data_grid(years = c(0:20),
            forest_type,
            genus_species = sp_1,
            .model = growth_model) %>% 
  add_epred_draws(object = growth_model, ndraws = NULL,
                  re_formula = ~ (0 + forest_type |genus_species),
                  allow_new_levels = FALSE)


all_gr <- 
  all_preds %>% 
  group_by(forest_type, genus_species, years) %>% 
  point_interval(.epred,
                 .width = 0.95,
                 .point = median,
                 .interval = hdi,
                 na.rm = TRUE) %>%
  group_by(forest_type, genus_species) %>% 
  mutate(lag_epred = lag(.epred, n = 1, order_by = years)) %>% 
  rowwise() %>% 
  mutate(growth_cmyr = .epred - lag_epred) %>% 
  ungroup()

all_gr %>% 
  filter(genus_species == sp_1) %>% 
  ggplot(aes(x = .epred, y = growth_cmyr, 
             xmin = .lower, xmax = .upper)) +
  geom_path(linewidth = 1,
            alpha = 1,
            linetype = 2) +
  xlab("Basal diameter cm") +
  ylab("Growth rate cm/yr") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))
```

```{r}
sp1_gr_s <- 
  sp1_preds_s %>% 
  group_by(plant_id, years) %>% 
  point_interval(.epred,
                 .width = 0.95,
                 .point = median,
                 .interval = hdi,
                 na.rm = TRUE) %>%
  group_by(plant_id) %>% 
  mutate(lag_dbh_pred = lag(.epred, n = 1, order_by = years)) %>% 
  rowwise() %>% 
  mutate(growth_cmyr = .epred - lag_dbh_pred) %>% 
  ungroup()
```

```{r}
sp1_gr_s %>% 
  ggplot(aes(x = .epred, y = growth_cmyr)) +
  geom_line(aes(group = plant_id), 
            alpha = 0.3,
            colour = "forestgreen",
            linewidth = 1,
            stat = "smooth") +
  xlab("Basal diameter cm") +
  ylab("Growth rate cm/yr") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(limit = c(0, NA), expand = c(0, 0))
```

```{r}
all_gr_sp1_s <- 
  all_gr %>% 
  filter(genus_species == sp_1 & forest_type == "secondary")

p3 <- 
  ggplot() +
  geom_line(data = sp1_gr_s,
            aes(x = .epred, y = growth_cmyr,
                group = plant_id), 
            alpha = 0.3,
            stat = "smooth",
            colour = "forestgreen",
            linewidth = 1) +
  geom_path(data = all_gr_sp1_s,
            aes(x = .epred, y = growth_cmyr), 
            linewidth = 1,
            alpha = 1,
            linetype = 2) +
  xlab("Basal diameter cm") +
  ylab("Growth rate cm/yr") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(limit = c(0, NA), expand = c(0, 0))

p3
```

# Survival

```{r}
survival_model <- 
  readRDS(here::here("output", "models", 
                     "survival", "survival_model_impute.rds"))
```


```{r}
survival_data <-
  readRDS(here::here("data", "derived", "data_survival.rds"))
```

## Fourth panel

```{r}
p4 <- 
  data %>% 
  filter(genus_species == sp_1 & 
           forest_type == "secondary" & cohort == 1) %>% 
  filter(plant_id %in% 
           sample(unique(growth_data_sp1_s$plant_id), 30)) %>% 
  mutate(survival = ifelse(survival == 0, "Dead", "Alive")) %>% 
  ggplot(aes(y = plant_id, x = years,
             shape = as.ordered(survival))) +
  geom_point(size = 2, colour = "grey20", stroke = 0.75) +
  scale_shape_manual(values = c(19, 4)) +
  theme(axis.text.y = element_blank(),
        legend.position = "top",legend.justification="left",
        legend.title = element_blank()) +
  xlab("Years") +
  ylab("Seedling ID")

p4
```

## Fifth panel

```{r}
survival_data %>% 
  mutate(survival = 0) %>% 
  filter(genus_species == sp_1) %>%
  ggplot(aes(x = dbase_mean)) +
  geom_dots(aes(y = survival,
                side = ifelse(survival == 0, "top", "bottom")), 
            pch = 19, color = "grey20",
            overlaps = "nudge") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), breaks = c(0,1)) +
  ylab("Survival") +
  xlab("Basal diameter")

```

```{r}
grp_eff_im <- 
  get_variables(survival_model) %>%
  str_subset(pattern = "^r_genus_species")

pred_df_sz_sp <- 
  survival_data %>%
  data_grid(bsp_timetolastalive_midbase_mean_sc = 
              seq(0.1, 200.1, 1)) %>%
  mutate(.chain = NA) %>%
  mutate(shape_timetolastalive = NA) %>%
  mutate(.draw = NA) %>%
  mutate(.iteration = NA) %>%
  mutate(b_timetolastalive_forest_typeprimary = NA) %>%
  mutate(b_timetolastalive_forest_typesecondary = NA)

pred_df_sz_sp[grp_eff_im] <- NA

mcmc_df_sz_sp <-
  survival_model %>%
  spread_draws(shape_timetolastalive, `r_.*`, 
               b_timetolastalive_forest_typeprimary,
               b_timetolastalive_forest_typesecondary,
               bsp_timetolastalive_midbase_mean_sc,
                 regex = TRUE) %>% 
  mutate(bsp_timetolastalive_midbase_mean_sc = NA)  %>% 
  rowwise() %>% 
  mutate(across(contains(",forest_typeprimary]"),
                 ~ .x + b_timetolastalive_forest_typeprimary)) %>% 
  mutate(across(contains(",forest_typesecondary]"),
                 ~ .x + b_timetolastalive_forest_typesecondary))

curves_df_sz_sp <-
  union(pred_df_sz_sp, mcmc_df_sz_sp) %>%
  expand(
    nesting(
      .chain,
      .iteration,
      .draw,
      b_timetolastalive_forest_typeprimary,
      b_timetolastalive_forest_typesecondary,
      shape_timetolastalive,
      `r_genus_species__timetolastalive[Hopea_sangal,forest_typeprimary]`,
      `r_genus_species__timetolastalive[Hopea_sangal,forest_typesecondary]`
    ),
    bsp_timetolastalive_midbase_mean_sc
  ) %>%
  filter(!is.na(bsp_timetolastalive_midbase_mean_sc)) %>%
  filter (!is.na(.draw)) %>%
  # survival curves
  mutate(across(contains("r_genus_species__timetolastalive["),
                 ~ exp (-(((bsp_timetolastalive_midbase_mean_sc - 0) / exp (.x))^shape_timetolastalive)))) 
  
plotting_data_sp <- 
  curves_df_sz_sp %>% 
  pivot_longer(contains("r_genus_species__")) %>% 
  mutate(genus_species = str_split_i(string = name, pattern ="\\[", i = 2)) %>% 
  mutate(genus_species = str_split_i(string = genus_species, pattern =",", i = 1)) %>% 
  mutate(forest_type = str_split_i(string = name, pattern =",", i = 2)) %>% 
  mutate(forest_type = ifelse(forest_type== "forest_loggedprimary]", "primary", "secondary")) 
```

```{r}
plotting_data_sp %>% 
  ggplot (aes (x = bsp_timetolastalive_midbase_mean_sc, 
               y = value, 
               colour = forest_type, 
               fill = forest_type)) +
  stat_lineribbon (.width = 0.95, alpha = 0.5) +
  ylab("Survival probability")+
  xlab("Basal diameter /cm") +
  facet_wrap(~genus_species, ncol = 3) +
  theme(legend.position = "bottom")
```

```{r}
surv_sp1 <-
  survival_data %>% 
  mutate(survival = 0) %>% 
  filter(genus_species == sp_1)

p5 <-
  ggplot() +
  geom_dots(data = filter(surv_sp1, forest_type == "secondary"),
         aes(x = dbh_mean, y = survival,
                side = ifelse(survival == 0, "top", "bottom")), 
            pch = 19, color = "grey20",
            overlaps = "nudge"
         ) +
  stat_lineribbon(data = filter(plotting_data_sp, forest_type == "secondary"), 
    aes(x = bsp_timetolastalive_midbase_mean_sc, 
               y = value), colour = "forestgreen", fill = "forestgreen",
               .width = 0.95, alpha = 0.7, show.legend = FALSE) +
  stat_lineribbon(data = filter(plotting_data_sp, forest_type == "secondary"), 
    aes(x = bsp_timetolastalive_midbase_mean_sc, 
               y = value), colour = "forestgreen", 
               .width = 0, show.legend = FALSE) +
  ylab("Survival")+
  xlab("Basal diameter cm") +
  theme(legend.position = "bottom") +
  scale_x_continuous(limits = c(0, 200), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), breaks = c(0, 1)) 

p5
```

# Combined panels

```{r}
#| fig-width: 15
#| fig-height: 10

p1 + p2 + p3 + p4 + p5 +
  patchwork::plot_layout(ncol = 3) +
  patchwork::plot_annotation(
    tag_levels = "a",
    title = "Hopea sangal",
    subtitle = "Secondary forest",
    theme = theme(
      plot.title = element_text(face = "italic")
      )
  )

```

