---
title: "Plotting priors vs posteriors for our growth model"
author: 'eleanorjackson'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
format: 
  gfm:
    toc: true
editor: source
execute:
  warning: false
---

```{r setup}
#| include: false

file_name <- knitr::current_input()

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.rmarkdown$", "", basename(file_name)), 
           "/", sep = "")
)

set.seed(123)
ggplot2::theme_set(ggplot2::theme_bw(base_size = 13))
```

```{r}
library("tidyverse")
library("tidybayes")
library("brms")
library("ggtext")
library("ggh4x")
```

```{r}
mod_gro <-
  readRDS(here::here("output", "models", 
                     "growth_model_base_p3_allo_priors5.rds"))
```

```{r}
prior_draws <- 
  prior_draws(mod_gro) %>% 
  select(contains("b_"))

post_draws <- 
  as_draws_df(mod_gro, variable = "^b_", regex = TRUE)

prior_post <- 
  bind_rows(prior = prior_draws, 
          posterior = post_draws,
          .id = "dist") %>% 
  pivot_longer(cols = contains("b_")) %>% 
  mutate(parameter = str_split_i(string = name, 
                                 pattern ="_", i = 2)) %>% 
  mutate(forest_type = case_when(
    grepl("logged", name) ~ "Logged forest",
    grepl("primary", name) ~ "Old-growth forest")) %>% 
  mutate(parameter = str_remove(string = parameter, 
                                 pattern ="logged")) %>% 
  mutate(parameter = str_remove(string = parameter, 
                                 pattern ="primary"))
  
```

```{r}

pal <-
  c("Logged forest" = "#e69f00", "Old-growth forest" = "#009e73")

prior_post %>% 
  mutate(dist = str_to_sentence(dist)) %>%
  mutate(dist = factor(dist, levels = c("Prior", "Posterior"))) %>%
  mutate(name = case_when(
    parameter == "logA" ~ "log <i>A</i>, Asymptotic basal<br>diameter (mm)",
    parameter == "logkG" ~ "log <i>k<sub>G</sub></i>, Growth rate<br>coefficient",
    parameter == "Ti" ~ "<i>T<sub>i</sub></i>, Time to reach max<br>growth rate (years)"
  )) %>%
  mutate(value = case_when(
    parameter == "logA" ~ value,
    parameter == "logkG" ~ value,
    parameter == "Ti" ~ value
  )) %>%
  filter(value < 50) %>% 
  filter(value > -50) %>% 
  ggplot(aes(x = value, fill = forest_type)) +
  geom_density(alpha = 0.5) +
  ggh4x::facet_grid2(dist~name, scales = "free", independent = "all") +
  scale_fill_manual(values = pal, breaks = ~ .x[!is.na(.x)]) +
  theme(legend.position = "bottom",
        strip.text = element_markdown(),
        legend.title = element_blank())
```

```{r}
prior_post %>% 
  filter(parameter == "logA") %>% 
  mutate(A = exp(value)) %>% 
  ggplot(aes(x = A, fill = forest_type)) +
  geom_density(alpha = 0.5) +
  facet_wrap(dist~parameter, scales = "free") +
  labs(x = "Diameter at base (mm)") +
  xlim(c(0,500))
```

```{r}
prior_post %>% 
  filter(parameter == "Ti") %>% 
  ggplot(aes(x = value, fill = forest_type)) +
  geom_density(alpha = 0.5, bounds = c(-20, 20)) +
  facet_wrap(dist~parameter, scales = "free") +
  xlab("Years")
```

```{r}
prior_post %>% 
  filter(parameter == "logkG") %>% 
  drop_na(value) %>% 
  mutate(kG = exp(value)) %>% 
  rowwise() %>% 
  mutate(rgr = (kG / exp(1))*100) %>% 
  ggplot(aes(x = rgr, fill = forest_type)) +
  geom_density(alpha = 0.5) +
  facet_wrap(dist~parameter, scales = "free") +
  xlab("Relative growth rate (% year-1)") +
  xlim(c(0, 50))
```
