---
title: "Supplementary Information for including plot as a random effect"
author: 'eleanorjackson'
date: '`r format(Sys.time(), "%d %B, %Y")`' 
format: 
  gfm:
    toc: true
editor: source
execute:
  warning: false
---

```{r setup}
#| include: false

file_name <- knitr::current_input()

knitr::opts_chunk$set(
  fig.path =
    paste0("figures/", sub("\\.rmarkdown$", "", basename(file_name)), 
           "/", sep = "")
)

set.seed(20595)
ggplot2::theme_set(ggplot2::theme_bw(base_size = 13))
```

```{r}
library("tidyverse")
library("patchwork")
library("tidybayes")
library("brms")
library("modelr")
library("broom.mixed")
library("ggtext")
```

## Growth

```{r}
model_pl <- 
  readRDS(here::here("output", 
                   "models",
                   "growth_model_plot.rds"))

model_main <- readRDS(here::here("output",
                                 "models",
                                 "growth_model.rds"))
```

```{r}
model_pl$formula
```

```{r}
model_main$formula
```

```{r}
my_coef_tab <- 
  tibble(fit = list(model_main, model_pl),
         model = c("Original model", 
                   "with random effect\nof plot")) %>%
  mutate(tidy = purrr::map(
    fit,
    broom.mixed::tidy,
    effect = "fixed")) %>% 
  select(-fit) %>% 
  unnest(tidy) %>% 
  filter(!grepl("prior", term)) %>% 
  filter(!grepl("cut", term)) %>% 
  rowwise() %>% 
  mutate(parameter = pluck(strsplit(term, "_"),1, 1)) %>% 
  mutate(forest_type = pluck(strsplit(term, "_"), 1, 3)) %>%
  mutate(forest_type = str_remove(forest_type, "type")) %>%
  mutate(forest_type =
           case_when(
             forest_type == "primary" ~ "Old-growth forest",
             forest_type == "logged" ~ "Logged forest",
             .default = forest_type
             )) %>% 
  mutate(name = case_when(
    parameter == "logA" ~ "log <i>A</i>, Asymptotic<br>basal diameter",
    parameter == "logkG" ~ "log <i>k<sub>G</sub></i>, Growth<br>rate coefficient",
    parameter == "Ti" ~ "<i>T<sub>i</sub></i>, Time to reach<br>max growth rate"
  ))
```

```{r}
my_coef_tab %>% 
  ggplot(aes(x = forest_type, 
             y = estimate, 
             ymin = conf.low, ymax = conf.high)) +
  geom_pointrange(shape = 21, fill = "white") +
  labs(x = NULL,
       y = NULL) +
  coord_flip() +
  facet_grid(model~name, 
             scales = "free") +
  theme(strip.text = element_markdown())
```

```{r}
loo_compare(model_main, model_pl) %>% 
  data.frame() %>% 
  rownames_to_column(var = "model_name") %>% 
  ggplot(aes(x    = reorder(model_name, elpd_diff), 
             y    = elpd_diff, 
             ymin = elpd_diff - se_diff, 
             ymax = elpd_diff + se_diff)) +
  geom_pointrange(shape = 21, fill = "white") +
  coord_flip() +
  geom_hline(yintercept = 0, colour = "blue", linetype = 2) +
  labs(x = NULL, y = "difference from model with the largest ELPD", 
       title = "expected log predictive density (ELPD)")  
```

## Survival

```{r}
model_survival <-
  readRDS(here::here("output", "models",
                     "survival_model.rds"))
```

```{r}
model_survival$formula
```

```{r}
model_survival_pl <-
  readRDS(here::here("output", "models",
                     "survival_model_plot.rds"))
```

```{r}
model_survival_pl$formula
```

```{r}
loo_compare(model_survival, model_survival_pl) %>% 
  data.frame() %>% 
  rownames_to_column(var = "model_name") %>% 
  ggplot(aes(x    = reorder(model_name, elpd_diff), 
             y    = elpd_diff, 
             ymin = elpd_diff - se_diff, 
             ymax = elpd_diff + se_diff)) +
  geom_pointrange(shape = 21, fill = "white") +
  coord_flip() +
  geom_hline(yintercept = 0, colour = "blue", linetype = 2) +
  labs(x = NULL, y = "difference from model with the largest ELPD", 
       title = "expected log predictive density (ELPD)")  
```


```{r}
my_coef_tab_survival <- 
  tibble(fit = list(model_survival, model_survival_pl),
         model = c("Original model", 
                   "with random effect\nof plot")) %>%
  mutate(tidy = purrr::map(
    fit,
    broom.mixed::tidy,
    effect = "fixed")) %>% 
  select(-fit) %>% 
  unnest(tidy) %>% 
  filter(!grepl("prior", term)) %>% 
  rowwise() %>% 
  mutate(forest_type = pluck(strsplit(term, "_"), 1, 2)) %>%
  mutate(forest_type = str_remove(forest_type, "type")) %>% 
  mutate(forest_type =
           case_when(
             forest_type == "primary" ~ "log &mu;, Old-growth forest",
             forest_type == "logged" ~ "log &mu;, Logged forest",
             forest_type == "mean" ~ "&beta;, Basal diameter",
             .default = forest_type
             )) 
```

```{r}
my_coef_tab_survival %>% 
  ggplot(aes(x = forest_type, 
             y = estimate, 
             ymin = conf.low, ymax = conf.high)) +
  geom_pointrange(shape = 21, fill = "white") +
  labs(x = NULL,
       y = NULL) +
  coord_flip() +
  facet_grid(rows = vars(model), 
             scales = "fixed") +
  theme(strip.text = element_markdown(),
        axis.text.y = element_markdown())
```

```{r}
model_survival_pl
```

